# Generated by Django 5.2.10 on 2026-01-28 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this task', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the task', max_length=300)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the task')),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('DOING', 'Doing'), ('DONE', 'Done')], default='BACKLOG', help_text='Current status of the task', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level of the task', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this task was last modified')),
                ('assignee', models.ForeignKey(blank=True, help_text='User assigned to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
